#!/usr/bin/env node
/**
 * Generates the Caddy config that serves every thematic site × language from
 * the tree built by scripts/build-sites.js. Everything comes from existing
 * config, so nothing is listed twice:
 *
 *   hosts        deploy/environments.js  (domain per site, scheme, port)
 *   sites        config/sites.config.js
 *   languages    config/catalog.config.js
 *   apex rules   config/geo.js           (country → language, Accept-Language)
 *
 *   node scripts/caddyfile.js --env local              # print to stdout
 *   node scripts/caddyfile.js --env production --out deploy/Caddyfile
 *
 * Per host:
 *   <lang>.<domain>   static files from <root>/<site>/<lang>/, 404 page,
 *                     cache + security headers (ported from vercel.json)
 *   <domain>          redirect to the visitor's language: country header first
 *                     (only if the environment names one), then the first
 *                     published language in Accept-Language, then English —
 *                     the same order as pickLang() in config/geo.js.
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { LANGS } from '../config/catalog.config.js';
import { SITE_IDS } from '../config/sites.config.js';
import { COUNTRY_LANG, APEX_DEFAULT } from '../config/geo.js';
import { getEnvironment } from '../deploy/environments.js';
import { ROOT, parseArgs } from './lib/util.js';

/**
 * Accept-Language → first tag whose base language we publish. The lazy skip
 * group `(?:[^,]*,)*?` passes over foreign tags one by one, so the capture is
 * the earliest of ours in header order (as fromAcceptLanguage() in geo.js).
 * Quality values are ignored there too.
 */
export function acceptLanguageRegex(langs = LANGS) {
  return `(?i)^(?:[^,]*,)*?\\s*(${langs.join('|')})(?:-[^,;\\s]*)?\\s*(?:;[^,]*)?(?:,|$)`;
}

export function renderCaddyfile(envName, { root } = {}) {
  const env = getEnvironment(envName);
  const port = env.port ? `:${env.port}` : '';
  const address = (host) => (env.scheme === 'http' ? `http://${host}${port}` : `${host}${port}`);
  const url = (host) => `${env.scheme}://${host}${port}`;
  const siteRoot = root ?? (path.isAbsolute(env.root) ? env.root : path.resolve(ROOT, env.root));

  const out = [];
  out.push(
    `# Generated by scripts/caddyfile.js for the "${envName}" environment — do not edit by hand.`,
    '# Regenerate after changing deploy/environments.js or config/sites.config.js.',
    ''
  );

  const global = [];
  if (env.scheme === 'http') global.push('\tauto_https off');
  if (global.length) out.push('{', ...global, '}', '');

  out.push(
    '(static) {',
    '\tencode zstd gzip',
    '\theader {',
    '\t\tX-Content-Type-Options nosniff',
    '\t\tReferrer-Policy strict-origin-when-cross-origin',
    '\t\tX-Frame-Options SAMEORIGIN',
    '\t\t-Server',
    '\t}',
    '\theader /_astro/* Cache-Control "public, max-age=31536000, immutable"',
    '\theader /img/* Cache-Control "public, max-age=31536000, immutable"',
    '\theader /search-index.json Cache-Control "public, max-age=3600, must-revalidate"',
    env.compress ? '\tfile_server {\n\t\tprecompressed br gzip\n\t}' : '\tfile_server',
    '\thandle_errors {',
    '\t\trewrite * /404.html',
    '\t\tfile_server',
    '\t}',
    '}',
    ''
  );

  // Country header → language, grouped so each language is one matcher.
  const countriesByLang = {};
  for (const [country, lang] of Object.entries(COUNTRY_LANG)) {
    if (!LANGS.includes(lang)) continue;
    (countriesByLang[lang] ??= []).push(country);
  }

  for (const site of SITE_IDS) {
    const domain = env.domains[site];
    if (!domain) continue;

    out.push(`# ── ${site} ─────────────────────────────────────────`);
    for (const lang of LANGS) {
      out.push(
        `${address(`${lang}.${domain}`)} {`,
        `\troot * ${path.posix.join(siteRoot.split(path.sep).join('/'), site, lang)}`,
        '\timport static',
        '}',
        ''
      );
    }

    // Bare domain (and www. in production): send to the visitor's language.
    const apexHosts = [address(domain)];
    if (env.scheme === 'https') apexHosts.push(address(`www.${domain}`));
    out.push(`${apexHosts.join(', ')} {`);
    if (env.countryHeader) {
      for (const [lang, countries] of Object.entries(countriesByLang)) {
        out.push(
          `\t@country_${lang} header ${env.countryHeader} ${countries.join(' ')}`,
          `\tredir @country_${lang} ${url(`${lang}.${domain}`)}{uri} 302`
        );
      }
    }
    out.push(
      // Backtick-quoted: the Caddyfile lexer takes the regex verbatim.
      `\t@lang header_regexp al Accept-Language \`${acceptLanguageRegex()}\``,
      `\tredir @lang ${env.scheme}://{re.al.1}.${domain}${port}{uri} 302`,
      `\tredir * ${url(`${APEX_DEFAULT}.${domain}`)}{uri} 302`,
      '}',
      ''
    );
  }

  return out.join('\n');
}

const isCli = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname);
if (isCli) {
  const args = parseArgs();
  const envName = typeof args.env === 'string' ? args.env : 'local';
  const text = renderCaddyfile(envName, { root: typeof args.root === 'string' ? args.root : undefined });
  if (typeof args.out === 'string') {
    await writeFile(path.resolve(ROOT, args.out), text);
    console.log(`Wrote ${args.out}`);
  } else {
    process.stdout.write(text);
  }
}
